name: fuzhana

services:
  web:
    build: .
    container_name: fuzhana_web
    hostname: fuzhana_web
    ports:
      - "3000:80"
    volumes:
      - ./:/server
  db:
    image: mysql:latest
    container_name: fuzhana_db
    hostname: root
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data: