name: fuzhana

services:
  db:
    image: mysql:latest
    container_name: fuzhana_db
    hostname: fuzhana_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    container_name: fuzhana_nginx
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    container_name: fuzhana_php
    image: php:8-fpm
    volumes:
      - ./:/var/www/html
volumes:
  db-data: